pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                bat 'cd ci-demo && "C:\\Users\\prateekmhaske\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\pip.exe" install -r requirements.txt'
            }
        }

        stage('Unit Tests') {
            steps {
                bat 'cd ci-demo && "C:\\Users\\prateekmhaske\\AppData\\Local\\Programs\\Python\\Python312\\python.exe" -m pytest test_app.py --junitxml=unit-report.xml'
            }
            post {
                always {
                    junit 'ci-demo/unit-report.xml'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'cd ci-demo && docker build -t myapp:%BUILD_NUMBER% .'
            }
        }

        stage('Deploy Container') {
            steps {
                bat 'docker run -d -p 5000:5000 myapp:%BUILD_NUMBER%'
            }
        }
    }
}
